# Generated by Django 3.1.5 on 2021-02-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_skill_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit_info',
            name='jobUrl',
            field=models.CharField(max_length=500),
        ),
    ]
