# Generated by Django 3.1.5 on 2021-02-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_auto_20210201_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit_info',
            name='job',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='recruit_info',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='recruit_info',
            name='total_skill',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='recruit_info',
            name='total_skill_literal',
            field=models.CharField(max_length=300),
        ),
    ]
