# Generated by Django 3.1.5 on 2021-02-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0004_auto_20210201_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit_info',
            name='jobUrl',
            field=models.CharField(max_length=1000),
        ),
    ]
